### ISSUE TITLE
Never seen afro hair guy in IT industry area.

### ISSUE THREAD

**Issue by harutama** [iwate/hairstyle#3]
There is the opinion about IT guy's hair.
https://twitter.com/naoto_matsumoto/status/640755863611797505
How you think about it?

**Comment by kanreisa** [comment]
+1

**Comment by iwate** [comment]
Ah.. Nice guy who has afro hair is working in same floor.
So, It is not good to resemble his silhouette.
I want to change my hair to other hairstyle.

**Comment by kanreisa** [comment]
damn

**Comment by iwate** [comment]
@kanreisa (・´з`・)

**Comment by harutama** [comment]
![bs_20](https://cloud.githubusercontent.com/assets/1632018/9737349/25b6d224-5681-11e5-9615-9c5cea201c40.gif)
